# Generated by Django 4.2.28 on 2026-02-28 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=1000, verbose_name='Стартовий URL')),
                ('depth', models.PositiveIntegerField(default=1, verbose_name='Глибина сканування')),
                ('status', models.CharField(choices=[('PENDING', 'Очікує'), ('RUNNING', 'Виконується'), ('COMPLETED', 'Завершено'), ('FAILED', 'Помилка')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_unique_links', models.PositiveIntegerField(default=0, verbose_name='Всього унікальних посилань')),
                ('broken_links_count', models.PositiveIntegerField(default=0, verbose_name='Кількість битих')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Детальні результати')),
                ('finished_at', models.DateTimeField(auto_now_add=True, verbose_name='Час завершення')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scanner.scantask')),
            ],
        ),
    ]
